version: "3.7"

services:
  app:
    image: ruby
    command: bash -c 'bundle install && ruby import_from_csv.rb && ruby server.rb'
    ports: 
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: medical_records
  
  postgres:
    image: postgres
    volumes:
      - medical_records-postgres-data:/var/lib/postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: medical_records

  test:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb

volumes:
  medical_records-postgres-data:
