version: "3.7"

services:
  app:
    image: ruby
    command: bash -c 'bundle install && ruby import_from_csv.rb && ruby server.rb'
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - test
      - myredis
      - sidekiq
    working_dir: /app
    volumes:
      - ./:/app
      - bundle:/usr/local/bundle
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: medical_records
  
  postgres:
    image: postgres
    volumes:
      - medical_records-postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: medical_records

  test:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
  
  myredis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/var/lib/redis

  sidekiq:
    image: ruby
    command: bash -c 'bundle install && sidekiq -r '../server.rb' -c 8'
    working_dir: /app/sidekiq
    volumes:
      - ./:/app
      - bundle:/usr/local/bundle
    depends_on:
      - myredis
      - postgres
      - test

volumes:
  medical_records-postgres-data:
  bundle:
  redis-data:
